### ISSUE TITLE
remove wiki tab

### ISSUE THREAD

**Issue by cordoval** [robertotru/ToInlineStyleEmailBundle#13]

**Comment by cordoval** [comment]
@robertotru could you please grant more power to @Richtermeister so he can remove the unused wiki tab from the repo? it is just a checkbox under settings

**Comment by Richtermeister** [comment]
Or just remove that wiki yourself. I don't need to own this puppy ;) Either way.

**Comment by Richtermeister** [comment]
Actually, with more powers I could update the commit hooks to tap into Packagist tag updates and Travis.

**Comment by cordoval** [comment]
bump @robertotru feel free to assign me as maintainer as well i can do these tasks too
