### ISSUE TITLE
Symfony3

### ISSUE THREAD

**Issue by khasinski** [robertotru/ToInlineStyleEmailBundle#20]
I have a following warning in Sf2.8 which blocks me from upgrading to 3:

```
Defining the getGlobals() method in the "inlinecss" extension without explicitly implementing Twig_Extension_GlobalsInterface is deprecated since version 1.23.
```

**Comment by crussell52** [comment]
@khasinski, I just addressed this in https://github.com/robertotru/ToInlineStyleEmailBundle/pull/21

**Comment by Richtermeister** [comment]
Thanks @khasinski for reporting and @crussell52 for fixing. I tagged a new release ```1.2```. Let me know if you're running into any issues with it.
