### ISSUE TITLE
Interface 'Twig_Extension_GlobalsInterface' not found in InlineCssExtension.php on line 19

### ISSUE THREAD

**Issue by zia-newversion** [robertotru/ToInlineStyleEmailBundle#22]
I must confess this is my first time using ToInlineStyleEmailBundle. I am using `@dev-master` and have encountered this issue during `php app/console assetic:dump`. However, when I remove

```
 [...] implements \Twig_Extension_GlobalsInterface
```

from InlineCssExtension.php:19, it seems to work fine. I have looked it up but can't find this exact issue with anyone else. I did come across [this](http://twig.sensiolabs.org/doc/deprecated.html#extensions) which might mean the version of SensioDistributionBundle I'm using (`~3.0.12`) or the AsseticBundle (`~2.3`) might not be recent enough(?) However I can't change any of the deps because I'm afraid everything else will fall apart. 

However because I'm inexperienced, it's most probably something that I'm doing wrong. However, I would like to get to the bottom of this so if someone could help me out. So this is more of a quest than an _issue_. Going right to creating an issue on GitHub isn't an ideal thing to do but I couldn't find another forum for discussion on this issue.

**Comment by smarques** [comment]
+1 same problem here

**Comment by zia-newversion** [comment]
Hi, coming back to this issue, surprised to see it's still open. I forgot about this. I encountered this working on a PHP project. I am no longer working with the project, or with PHP so it's not possible for me to do a follow up on this issue. I would appreciate if someone else encountering the problem could take over. Or if the maintainers reviewed this and resolved/closed it.

**Comment by Syam** [comment]
Meet same error in a Symfony 2.7 context.

**Comment by cordoval** [comment]
symfony2.7 could have required a very old twig @Syam 

this is a non issue
