### ISSUE TITLE
{% inlinecss note working (with fix)

### ISSUE THREAD

**Issue by Mika56** [robertotru/ToInlineStyleEmailBundle#4]
Hi,

I was trying to use {% inlinecss within my code, but it wasn't working.
I am having this line at the top of my Twig template :

```
{% inlinecss "@TestTestBundle/Resources/views/Clients/client1/layout1.css" %}
```

While the CSS is correctly loaded, I was getting the "The CSS must be set" error.
Eventually, the ToInlineStyleEmailConverter::inlineCSS function was just setting the HTLM and CSS for $this->cssToInlineStyles, instead of it's own variables.

So, in ToInlineStyleEmailConverter, lines 208 and 209, you just have to remove "->cssToInlineStyles", and everything while work.

I could have sent a PR for this, but I'm at work and I don't have the time to fork, install GitHub, make the changes, commit :wink: 

Mikael.

**Comment by cordoval** [comment]
this ticket is very old @Mika56 can you please confirm or elaborate or tell us if you can reproduce this or if it is still relevant? Thanks :baby:

**Comment by cordoval** [comment]
@Mika56 is this a duplicate already ?

**Comment by Mika56** [comment]
Hi,
For some reason I didn't get, or missed, the notification for your question back in... 2015 😄 
I have to admit I'm not even sure to know what project I was using your library for, nor if this still applies.

**Comment by cordoval** [comment]
👍 @Mika56
